name: Build EXE and Upload

on:
  schedule:
    - cron: '0 10 * * 1'  # a) co poniedziałek o 10:00 UTC
  push:
    branches:
      - master           
  workflow_dispatch:      

jobs:
  build:
    runs-on: windows-latest  

    defaults:
      run:
        shell: bash

    steps:
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
            name: built-exe
            path: dist/*.exe


      - name: Install dependencies
        run: ./installResources.sh

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py  # lub odpowiednia komenda do budowania

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/*.exe
