name: Build EXE and Upload

on:
  schedule:
    - cron: '0 10 * * 1'  # a) co poniedziałek o 10:00 UTC
  push:
    branches:
      - master
  workflow_dispatch:       

jobs:
  build:
    runs-on: windows-latest  # najnowszy Windows

    defaults:
      run:
        shell: bash    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./installResources.sh

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py 

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/*.exe
